### ISSUE TITLE
More detailed Xcode Build Instructions on Fresh Machine

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/Bitcoin-Standup#13]
Xcode will not build on a fresh machine after clone, it gives a warning icon. When you click on warning icon it will list 3 items to fix, and there is an option to automatically fix it. Unfortunately, I lost the screen shots so this will need to be investigated to document for people who don't normally use Xcode.

**Comment by Fonta1n3** [comment]
When I run `git clone https://github.com/MikeMcQuaid/strap` on my fresh Catalina VMWare it prompts me to install XCode command line tools right away. It then downloads without issue and when I run strap.sh it works fine. I do not install XCode.app on the virtual machine.

Will have to try and reproduce what you are experiencing.

**Comment by ChristopherA** [comment]
I built the app on the VM after strap ends using `brew install mas`  `mas 497799835` (which longer term will not be necessary as someone will hopefully just download the app), but the error I'm experiencing I think will happen the first time xcode is used on a new machine with a fresh dowloaded repo.

**Comment by Fonta1n3** [comment]
understood, will try mas out and update the readme

**Comment by Fonta1n3** [comment]
closing this as its on the wrong repo and no longer relevant.
