### ISSUE TITLE
Verify Button after Standup

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/Bitcoin-Standup#14]

**Comment by ChristopherA** [comment]
You should ask the user to verify the install and display the results after the Standup button, rather than at the end of the list of buttons.

**Comment by ChristopherA** [comment]
I'd also suggest you say exactly what was verified. For instance, I'm not sure you are verifying the tor download.

**Comment by Fonta1n3** [comment]
I moved the button and in addition check the sigs during the StandUp script so that the script will terminate before unpacking the tarball if the sigs do not match.
