### ISSUE TITLE
QR Code Display Problems

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/Bitcoin-Standup#15]
One minor problem is that the QR code is not in the middle of the screen on my small MacBook Air laptop. I also use even smaller window sizes when I use VWware with macOS.

The larger issue is that we've had problems when we did the Airgap standards for the best practices for showing the QR code on a Mac display, as some lower resolution cameras have a difficulty with it (especially another Mac). I know that more contrast is often needed, so green on black is probably not ideal.

Ask @msgilligan (who was scanning from a Mac onto his macOS laptop walet) and @wolfmcnally their thoughts.

**Comment by Fonta1n3** [comment]
Latest PR reduces the size significantly and changes the color to black and white.

**Comment by msgilligan** [comment]
Yeah, we found black & white worked much better than black and light grey. Laptop webcams tend to have lower resolution than modern mobile phones so they can be  bit of a corner case.
