### ISSUE TITLE
New install should display what kind of node this is

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/Bitcoin-Standup#16]
Before you startup Bitcoin-QT, you should be prompted to ask what kind of node that wish to standup. Pruned, txindex, reg-test/testnet/mainnet, etc. Probably should warn people with rough estimates as to the size and time to download/sync each.

**Comment by ChristopherA** [comment]
Probably a no-wallet option as well.

**Comment by ChristopherA** [comment]
Current version of app config installs a full Testnet with txindex at a little over 30GB. I don't have timing of sync, but started before I went to bed and was sync'ed by the time I got up. On my other mac full node with txindex the size ~310GB. Regtest size is negligable (kb).

**Comment by Fonta1n3** [comment]
Have added in a modal alert when user clicks "StandUp" in the latest PR that informs user what kind of node will be installed, approximately how much space is needed and inform them they can go to settings to customize specific options to suite their needs.

Still need to add a disablewallet option to settings.
