### ISSUE TITLE
Standup Node's Name in QR

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/Bitcoin-Standup#20]
We should probably set the name of the node in the app (default should be from "<Username>'s Standup Node"), allow someone to change this in settings, and communicate this in the QR code, which can be an optional field.

-- Christopher Allen

**Comment by Fonta1n3** [comment]
added in latest PR

**Comment by ChristopherA** [comment]
We need to update README doc on this, and talk about it with the other parties, seeking their opinion and if there are other related missing requirements. (we should compile a list of github @ for other people that are supporting or considering supporting this, and add them as cc/ to future PRs)
