### ISSUE TITLE
Discovering Latest Bitcoin

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/Bitcoin-Standup#21]
Bitcoin 0.19 is out today. Not sure what is the best way for Fully Noded to be sure it has the latest. Maybe some type of simple signed file on Github with the current version number tested with Bitcoin Standup?

**Comment by Fonta1n3** [comment]
This is a great idea, are you ok with using githubs api to check for new versions of bitcoin? I see bitcoin.org still has not released the binary download for release 0.19.0 and still shows 0.18.1 on the main download page. Even the [link](https://bitcoin.org/bin/bitcoin-core-0.19.0/) for downloading 0.19.0 still shows it as test releases only, unless I am missing something. It would be great if we could bypass bitcoin.org altogether and build directly from source.

**Comment by Fonta1n3** [comment]
The initial capability has been added in latest version but requires one of the github contributors to manually update [this file](https://github.com/Fonta1n3/Bitcoin-Standup/blob/master/StandUp/JSON/SupportedVersion.json) which StandUp queries via the github api.
