### ISSUE TITLE
Ability to recognize Bitcoin upgrade available

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/Bitcoin-Standup#22]
Related to #21 is Bitcoin Standup should recognize it has an old version of bitcoin installed, and offer to upgrade it.

**Comment by Fonta1n3** [comment]
The basic ability for the app to do this has been added in the most recent version. It is just an initial approach, and can be improved. 

One issue is that bitcoin.org is still only showing test releases of of 0.19.0, even though the official version was released on github.
