### ISSUE TITLE
Add UnStandup Button to Settings

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/Bitcoin-Standup#24]
It would be useful if there was a button in the Settings that removed all traces of Standup, so that it could be testing/reinstalled from scratch.

-- Christopher Allen

**Comment by ChristopherA** [comment]
Also possible option to keep the blockchain data, just delete apps and scripts.

**Comment by Fonta1n3** [comment]
In latest PR I added two buttons in settings, one for "Standing Down" and one to remove the bitcoin directory.

**Comment by ChristopherA** [comment]
There was an error in log when I did StandDown, something about unknown cask, but when it was done I did not see a log button to see what it was.

**Comment by ChristopherA** [comment]
Oh, the log button moved. But I can't copy any text there. The error was: "Error: No such keg: /usr/local/tor". Is this just a confirmation you've removed tor?

**Comment by Fonta1n3** [comment]
I believe so, I did get the same error. It’s probably redundant to use ‘brew uninstall tor’ and then ‘brew remove tor’. Will investigate and also will make the console text selectable.
