### ISSUE TITLE
Document "Authenticate with Tor V3 Pubkey"

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/Bitcoin-Standup#26]
We should probably say a bit more about tor, and in particular what is the purpose of this setting option.

We also should probably display in main window what is the tor onion address for this node just for reference.

**Comment by Fonta1n3** [comment]
this was added in latest PR

**Comment by Fonta1n3** [comment]
Considering the sensitivity of the onion address I am not sure it is good practice to display it in plain text unnecessarily, just my opinion. What would be the benefit of displaying it?
