### ISSUE TITLE
Standup Init Message not respecting Standup Config choice

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/Bitcoin-Standup#37]
In current master, compiled latest Xcode for Catalina, before clicking on the standup button, I set it to not-pruned, tx-index, and mainnet:

<img width="578" alt="Screen Shot 2019-12-03 at 8 12 14 PM" src="https://user-images.githubusercontent.com/69103/70112192-64ce9b80-1609-11ea-9c60-654fbe65bdc3.png">

When I click on standup button, it doesn't say this, it says "StandUp installs and configures a fully indexed Bitcoin Core v0.19.0.1 testnet node and Tor v0.4.1.6" 

<img width="532" alt="Screen Shot 2019-12-03 at 8 15 16 PM" src="https://user-images.githubusercontent.com/69103/70112284-af501800-1609-11ea-80ea-f33cb3e99942.png">

**Comment by Fonta1n3** [comment]
This was addressed in https://github.com/BlockchainCommons/Bitcoin-Standup/pull/43
