### ISSUE TITLE
Standup doesn't configure tor or bitcoin.conf for the user

### ISSUE THREAD

**Issue by watersnake1** [BlockchainCommons/Bitcoin-Standup#67]
To make Standup leave fewer steps to the user, Standup should configure /etc/tor/torrc and bitcoin.conf properly. On my machine (Ubuntu 18.04), I had to perform the following after running standup: 
change `HiddenServicePort 1309 127.0.0.1:8332` to `HiddenServicePort 8332 127.0.0.1:8332` in torrc
create a directory `~/.tor` that belongs to the user debian-tor
add the following to bitcoin.conf:
`proxy = 127.0.0.1:9050 \n listen=1 \n bind=127.0.0.1`
Standup should provide these settings to the user because otherwise connecting to the newly installed node remotely (such as via FullyNoded) will not work.

**Comment by Fonta1n3** [comment]
In our tests Standup does do those things, you certainly do not need to change the `HiddenServicePort`, `1309` works fine what is important for it to work is `127.0.0.1:8332`, the virtual port can be any port. Standup is very much meant for a clean install e.g. a machine that has never had Tor or Bitcoin Core installed. The conf settings `proxy = 127.0.0.1:9050 \n listen=1 \n bind=127.0.0.1` are not relevant to remotely connecting to your nodes rpcport, we avoid them by default as it slows down IBD, it should be an enhancement that we make them optional.

**Comment by Fonta1n3** [comment]
Please do try it out on a fresh install, ideally Debian 10. If you have issues with them please do raise them [here](https://github.com/BlockchainCommons/Bitcoin-Standup-Scripts) on the dedicated repo for those scripts.
